AWSTemplateFormatVersion: '2010-09-09'
Description: Template para desplegar un servicio Java en Docker y una instancia de PostgreSQL

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: api-seguros-jmg
      ContainerDefinitions:
        - Name: api-seguros-jmg
          Image: jonathanvictorica/api-seguros-jmg:v1
          PortMappings:
            - ContainerPort: 8080

  Service:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 12.5
      MasterUsername: your_master_username
      MasterUserPassword: your_master_password
      DBName: your_database_name
      AllocatedStorage: 20
      MultiAZ: false
      PubliclyAccessible: true