apiVersion: v1
kind: Service
metadata:
  name: jmg-seguros-lb-service
spec:
  selector:
    app: api-seguros-jmg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020  # Puerto en el que tu aplicación dentro del pod está escuchando
  type: LoadBalancer