
spring:
  r2dbc:
    url: ${BD_URL}
    username: ${BD_USER}
    password: ${BD_PASS}
    pool:
      initial-size: 10
      max-size: 20

springfox:
  documentation:
    swagger-ui:
      enabled: true
#OpenAPI Properties
springdoc:
  api-docs:
    swagger-ui:
      path: /swagger-ui.html
  enabled: true
server:
  port: 8020
