version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: my_postgresql_db
    environment:
      POSTGRES_DB: jmg_api_seguros_dev
      POSTGRES_USER: api_seguros_user
      POSTGRES_PASSWORD: api_seguros_pass
    ports:
      - "5432:5432"