version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: my_postgresql_db
    environment:
      POSTGRES_DB: api_seguros
      POSTGRES_USER: api_seguros_user
      POSTGRES_PASSWORD: api_seguros_pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data